export const config = {
  port: Number(process.env.PORT || 3000),
  birdeyeApiUrl: process.env.BIRDEYE_API_URL || 'https://public-api.birdeye.so',
  birdeyeApiKey: process.env.BIRDEYE_API_KEY || '',
  heliusApiUrl: process.env.HELIUS_API_URL || 'https://mainnet.helius-rpc.com',
  heliusApiKey: process.env.HELIUS_API_KEY || '',
  rugcheckApiUrl: process.env.RUGCHECK_API_URL || 'https://api.rugcheck.xyz',
  discoverySeconds: Number(process.env.DISCOVERY_SECONDS || 60),
  refreshSeconds: Number(process.env.REFRESH_SECONDS || 30),
  rugcheckRefreshMinutes: Number(process.env.RUGCHECK_REFRESH_MINUTES || 5),
  whitelistExitHours: 24,
  staleLowCapHours: 2,
  lowCapThreshold: 30000,
  immediateMinFdv: Number(process.env.IMMEDIATE_MIN_FDV || 10000),
  blacklistTtlMinutes: 15,
  maxNewListingPageSize: Number(process.env.NEW_LISTING_PAGE_SIZE || 50),
  lpOverFdvThreshold: Number(process.env.LP_FDV_THRESHOLD_PERCENT || 10) / 100,
  lpOverFdvUpperThreshold: Number(process.env.LP_FDV_MAX_THRESHOLD_PERCENT || 50) / 100,
  httpTimeoutMs: Number(process.env.HTTP_TIMEOUT_MS || 8000),
  tickBatchSize: Number(process.env.TICK_BATCH_SIZE || 50),
  maxTrackedTokens: Number(process.env.MAX_TRACKED_TOKENS || 3000),
  maxStateRows: Number(process.env.MAX_STATE_ROWS || 300),
  webhookUrl: process.env.WEBHOOK_URL || 'https://43.165.171.121:8000/webhook/token',
  webhookTimeoutMs: Number(process.env.WEBHOOK_TIMEOUT_MS || 5000),
};
