export const config = {
  port: Number(process.env.PORT || 3000),
  birdeyeApiUrl: process.env.BIRDEYE_API_URL || 'https://public-api.birdeye.so',
  birdeyeApiKey: process.env.BIRDEYE_API_KEY || '',
  heliusApiUrl: process.env.HELIUS_API_URL || 'https://mainnet.helius-rpc.com',
  heliusApiKey: process.env.HELIUS_API_KEY || '',
  rugcheckApiUrl: process.env.RUGCHECK_API_URL || 'https://api.rugcheck.xyz',
  discoverySeconds: Number(process.env.DISCOVERY_SECONDS || 60),
  refreshSeconds: Number(process.env.REFRESH_SECONDS || 30),
  whitelistExitHours: 24,
  staleLowCapHours: 2,
  lowCapThreshold: 30000,
  blacklistTtlMinutes: 15,
  maxNewListingPageSize: Number(process.env.NEW_LISTING_PAGE_SIZE || 50),
  lpBurnedThreshold: Number(process.env.LP_BURNED_THRESHOLD || 99.5),
  lpLockedThreshold: Number(process.env.LP_LOCKED_THRESHOLD || 95),
};
