export const config = {
  port: Number(process.env.PORT || 3000),
  birdeyeApiUrl: process.env.BIRDEYE_API_URL || 'https://public-api.birdeye.so',
  birdeyeApiKey: process.env.BIRDEYE_API_KEY || '',
  heliusApiUrl: process.env.HELIUS_API_URL || 'https://mainnet.helius-rpc.com',
  heliusApiKey: process.env.HELIUS_API_KEY || '',
  rugcheckApiUrl: process.env.RUGCHECK_API_URL || 'https://api.rugcheck.xyz',
  discoverySeconds: Number(process.env.DISCOVERY_SECONDS || 60),
  refreshSeconds: Number(process.env.REFRESH_SECONDS || 30),
  rugcheckRefreshMinutes: Number(process.env.RUGCHECK_REFRESH_MINUTES || 5),
  whitelistExitHours: 24,
  staleLowCapHours: 2,
  lowCapThreshold: 30000,
  blacklistTtlMinutes: 15,
  maxNewListingPageSize: Number(process.env.NEW_LISTING_PAGE_SIZE || 50),
  lpOverFdvThreshold: Number(process.env.LP_FDV_THRESHOLD_PERCENT || 10) / 100,
};
